# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('class_id', models.CharField(max_length=2)),
                ('semester', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=5)),
                ('vacancies', models.IntegerField()),
                ('registered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('U', 'Undergraduate'), ('G', 'Graduate')], max_length=1)),
                ('descryption', models.CharField(max_length=1024)),
                ('classes', models.ManyToManyField(to='dacParser.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('school', models.IntegerField()),
                ('course_type', models.CharField(max_length=4)),
                ('disciplines', models.ManyToManyField(to='dacParser.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='dacParser.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacParser.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('name', 'ra', 'school')]),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('code', 'name', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('code', 'class_id', 'year', 'semester')]),
        ),
    ]
