# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_id', models.CharField(max_length=2)),
                ('semester', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=5)),
                ('vacancies', models.IntegerField()),
                ('registered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=15)),
                ('course_type', models.CharField(max_length=4)),
                ('stu_offerings', models.ManyToManyField(to='dacParser.Offering')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('U', 'Undergraduate'), ('G', 'Graduate')], max_length=1)),
                ('descryption', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('code', 'name', 'type')]),
        ),
        migrations.AddField(
            model_name='offering',
            name='students',
            field=models.ManyToManyField(to='dacParser.Student'),
        ),
        migrations.AddField(
            model_name='offering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacParser.Subject'),
        ),
        migrations.AddField(
            model_name='offering',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacParser.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('name', 'ra', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='offering',
            unique_together=set([('subject', 'offering_id', 'year', 'semester')]),
        ),
    ]
