# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gda', '0003_auto_20160914_2355'),
        ('dacParser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gda.Questionnaire'),
        ),
    ]
