# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dacParser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='1d20e0aaa88650c5b18821f7de635053', max_length=37, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacParser.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacParser.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('student', 'discipline', 'token')]),
        ),
    ]
